import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Tutorial App',
  description: 'Generated by Eric',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <h1>Some Other Thing</h1>
        {children}
      </body>
    </html>
  )
}
